# Generated by Django 4.2.3 on 2023-08-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='заголовок')),
                ('content', models.TextField(blank=True, null=True, verbose_name='содержимое статьи')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='main/', verbose_name='превью (изображение)')),
                ('creation_date', models.DateField(blank=True, null=True, verbose_name='дата публикации')),
                ('number_views', models.IntegerField(default=0, verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'Блоговая запись',
                'verbose_name_plural': 'Блоговые записи',
            },
        ),
    ]
